#!/usr/bin/env bash

echo "Enabled script started"

echo "INSTANCES: $(jq -c -r '.myModule.instances' $VALUES_PATH)"
echo "COUNT: $(jq -r '.myModule.instances | length' $VALUES_PATH)"

count=$(jq -r '.myModule.instances | length' $VALUES_PATH)

if [[ $count -eq 0 ]] ; then
  echo "false" > $MODULE_ENABLED_RESULT
else
  echo "true" > $MODULE_ENABLED_RESULT
fi